version: '3.8'

services:
  patient-api:
    image: patient-api
    ports:
      - "8085:8085"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  note-api:
    image: note-api
    ports:
      - "8086:8086"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  risk-api:
    image: risk-api
    ports:
      - "8087:8087"

  client-ui:
    image: client-ui
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - patient-api
      - note-api
      - risk-api
